-- Enable DAP logging
require("options")
require("keymaps")
require("misc")
require("plugins.lazy")
require("plugins.colorscheme")
require("plugins.oilvim")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.harpoon")
require("plugins.colorizer")
require("plugins.web-tools")
require("plugins.hop")
require("plugins.codesnap")
require("plugins.neogit")
require("plugins.gitsigns")
require("plugins.blink")
require("plugins.lsp")
require("plugins.goto-preview")
require("plugins.dap")
require("plugins.refactoring")
require("plugins.rustacean-nvim")
require("plugins.go-nvim")
require("plugins.dressing")
require("plugins.dashboard")
require("plugins.cloak")
require("plugins.dad-ui")
require("plugins.hurl")
require("plugins.chatgpt")
require("plugins.codecompanion")
require("plugins.copilot")
require("plugins.snack")
-- require('plugins.trouble')
-- require('plugins.obsidian')
-- require('plugins.zenmode')
